export const samples = {
  accounts: [
    {
      key: "accounts-1",
      fields: {
        title: "Operating account",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "active",
        bank: "Example Commercial Bank",
        accountHint: "4821",
        currency: "CNY",
        balance: 128400,
        checkedAt: "2026-09-29T08:30:00+08:00",
        notes: "Book balance as of the stated check; not a live bank balance.",
      },
    },
    {
      key: "accounts-2",
      fields: {
        title: "Reserve account",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "active",
        bank: "Example Savings Bank",
        accountHint: "7604",
        currency: "CNY",
        balance: 68000,
        checkedAt: "2026-09-25T09:00:00+08:00",
        notes:
          "Last check is stale; obtain a new statement before relying on this amount.",
      },
    },
    {
      key: "accounts-3",
      fields: {
        title: "Foreign currency account",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "restricted",
        bank: "Example Trade Bank",
        accountHint: "1168",
        currency: "USD",
        balance: 7200,
        checkedAt: "2026-09-28T09:00:00+08:00",
        notes:
          "Restricted pending owner verification. Never combine USD and CNY totals.",
      },
    },
  ],
  checks: [
    {
      key: "checks-1",
      fields: {
        title: "Operating check - September 29",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "exception",
        account: "accounts-1",
        currency: "CNY",
        balance: 128400,
        bankBalance: 127900,
        checkedAt: "2026-09-29T08:30:00+08:00",
        evidence: "Statement ST-0929 (synthetic)",
        reason: "Bank balance is 500 lower than book; trace an unposted fee.",
        notes: "Do not adjust the ledger until source evidence is confirmed.",
      },
    },
    {
      key: "checks-2",
      fields: {
        title: "Reserve check - September 25",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "matched",
        account: "accounts-2",
        currency: "CNY",
        balance: 68000,
        bankBalance: 68000,
        checkedAt: "2026-09-25T09:00:00+08:00",
        evidence: "Statement ST-0925 (synthetic)",
        reason: "",
        notes: "Matched on the stated date only; a new check is due.",
      },
    },
    {
      key: "checks-3",
      fields: {
        title: "Foreign account check",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "pending",
        account: "accounts-3",
        currency: "USD",
        balance: 7200,
        bankBalance: null,
        checkedAt: "",
        evidence: "",
        reason: "No bank statement supplied.",
        notes: "No verified bank balance available.",
      },
    },
  ],
  payments: [
    {
      key: "payments-1",
      fields: {
        title: "September office rent",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "approved",
        account: "accounts-1",
        amount: 12000,
        currency: "CNY",
        due: "2026-10-03",
        approval: "Approval AP-028 (synthetic)",
        receipt: "",
        paidAt: "",
        invoice: "SYN-INV-RENT-09",
        notes: "Approved request; funds have not been transferred.",
      },
    },
    {
      key: "payments-2",
      fields: {
        title: "Equipment supplier installment",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "pending",
        account: "accounts-1",
        amount: 8600,
        currency: "CNY",
        due: "2026-10-05",
        approval: "",
        receipt: "",
        paidAt: "",
        invoice: "SYN-INV-EQ-26",
        notes: "Awaiting human approval and beneficiary verification.",
      },
    },
    {
      key: "payments-3",
      fields: {
        title: "Network service renewal",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "paid",
        account: "accounts-1",
        amount: 720,
        currency: "CNY",
        due: "2026-09-28",
        approval: "Approval AP-026 (synthetic)",
        receipt: "SYN-RC-NET-26",
        paidAt: "2026-09-28",
        invoice: "SYN-INV-NET-26",
        notes: "Synthetic bank receipt linked; matching ledger entry exists.",
      },
    },
    {
      key: "payments-4",
      fields: {
        title: "Reserve-account vendor payment",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "blocked",
        account: "accounts-2",
        amount: 3800,
        currency: "CNY",
        due: "2026-10-01",
        approval: "",
        receipt: "",
        paidAt: "",
        invoice: "",
        notes:
          "Invoice missing and account check is stale. Hold for verification.",
      },
    },
  ],
  ledger: [
    {
      key: "ledger-1",
      fields: {
        title: "Network renewal outgoing",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "reconciled",
        account: "accounts-1",
        payment: "payments-3",
        amount: 720,
        currency: "CNY",
        direction: "out",
        due: "2026-09-28",
        receipt: "SYN-RC-NET-26",
        invoice: "SYN-INV-NET-26",
        reason: "",
        notes: "Exact synthetic match to paid request and receipt.",
      },
    },
    {
      key: "ledger-2",
      fields: {
        title: "Workshop fee received",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "unmatched",
        account: "accounts-1",
        payment: "",
        amount: 16800,
        currency: "CNY",
        direction: "in",
        due: "2026-09-29",
        receipt: "SYN-RC-WS-26",
        invoice: "",
        reason: "Invoice reference not yet supplied.",
        notes: "Cash received, but not reconciled to customer invoice.",
      },
    },
    {
      key: "ledger-3",
      fields: {
        title: "Unposted bank charge",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "exception",
        account: "accounts-1",
        payment: "",
        amount: 500,
        currency: "CNY",
        direction: "out",
        due: "2026-09-29",
        receipt: "SYN-ST-0929-FEE",
        invoice: "",
        reason: "Bank charge is absent from approved book adjustments.",
        notes: "Investigate the daily check difference before posting.",
      },
    },
  ],
};
