export const appConfig = {
  appId: "busa-writer",
  appName: "Busa Writer",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Busa Writer",
    description: "Channel-ready content drafting and review desk",
    slug: "busa-writer",
  },
  airApp: { name: "Busa Writer", slug: "busa-writer-app", resourceKey: "busa-writer-app" },
  bases: [
    {
      key: "drafts",
      name: "Drafts",
      slug: "busa-writer-drafts",
      description: "Per-channel content drafts under human review",
      readLimit: 50,
      fields: [
        { slug: "draft-id", name: "Draft ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "batch-id", name: "Batch ID", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "format", name: "Format", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "hook", name: "Hook", type: "longtext", required: false },
        { slug: "cta", name: "CTA", type: "text", required: false },
        { slug: "hashtags", name: "Hashtags", type: "longtext", required: false },
        { slug: "title-options", name: "Title options", type: "longtext", required: false },
        { slug: "media-brief", name: "Media brief", type: "longtext", required: false },
        { slug: "source-notes", name: "Source notes", type: "longtext", required: false },
        { slug: "risk", name: "Risk", type: "longtext", required: false },
        { slug: "canonical-idea", name: "Canonical idea", type: "longtext", required: false },
        { slug: "source-summary", name: "Source summary", type: "longtext", required: false },
        { slug: "source-draft-path", name: "Source draft path", type: "text", required: false },
        { slug: "export-filename", name: "Export filename", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "busa-writer-settings",
      description: "Brand/audience/channel profile and the agent lock",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.count"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
