export const appConfig = {
  appId: "busa-product-hub",
  appName: "Busa Product Hub",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Busa Product Hub",
    description:
      "Product & certification hub for export/trade sellers: catalog/SKU master data, pricing, inventory, channel status (Amazon/Shopify/TikTok Shop/eBay), content readiness, compliance notes, lifecycle state, a certificate expiry tracker, and an approval-gated review queue (channel publish approvals, price-change review, quality holds, lifecycle decisions, and unsourced spec claims). The AirApp itself only ever decides on a review item (approve/request_changes/block) directly onto its own record -- it never creates a product, channel, inventory, or certificate row.",
    slug: "busa-product-hub",
  },
  airApp: { name: "Busa Product Hub", slug: "busa-product-hub-app", resourceKey: "busa-product-hub-app" },
  bases: [
    {
      key: "products",
      name: "Products",
      slug: "busa-product-hub-products",
      description:
        "One row per product/SKU: catalog identity, lifecycle/status, owner, vendor, launch date, image + gallery, tags, and JSON-encoded pricing/inventory-rollup/content/compliance blocks.",
      readLimit: 50,
      fields: [
        { slug: "product-id", name: "Product ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "sku", name: "SKU", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "subtitle", name: "Subtitle", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "lifecycle", name: "Lifecycle", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "vendor", name: "Vendor", type: "text", required: false },
        { slug: "launch-date", name: "Launch date", type: "text", required: false },
        { slug: "image", name: "Image URL", type: "text", required: false },
        { slug: "gallery", name: "Gallery (JSON array)", type: "longtext", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "pricing", name: "Pricing (JSON object)", type: "longtext", required: false },
        { slug: "inventory", name: "Inventory rollup (JSON object)", type: "longtext", required: false },
        { slug: "content", name: "Content readiness (JSON object)", type: "longtext", required: false },
        { slug: "compliance", name: "Compliance (JSON object)", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "channels",
      name: "Channels",
      slug: "busa-product-hub-channels",
      description:
        "One row per product x marketplace channel (Amazon/Shopify/TikTok Shop/eBay): listing id, status, price, buybox, content score, and channel issue note.",
      readLimit: 50,
      fields: [
        { slug: "channel-id", name: "Channel ID", type: "text", required: true },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "listing-id", name: "Listing ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "price", name: "Price", type: "number", required: false },
        { slug: "buybox", name: "Buybox", type: "text", required: false },
        { slug: "content-score", name: "Content score", type: "number", required: false },
        { slug: "issue", name: "Channel issue", type: "longtext", required: false },
        { slug: "next-step", name: "Next step", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "inventory",
      name: "Inventory",
      slug: "busa-product-hub-inventory",
      description:
        "One row per product x warehouse: on-hand/available/reserved/inbound units, inbound ETA, days of cover, and stock-risk status.",
      readLimit: 50,
      fields: [
        { slug: "inventory-id", name: "Inventory ID", type: "text", required: true },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "warehouse-id", name: "Warehouse ID", type: "text", required: false },
        { slug: "warehouse-name", name: "Warehouse name", type: "text", required: false },
        { slug: "on-hand", name: "On hand", type: "number", required: false },
        { slug: "available", name: "Available", type: "number", required: false },
        { slug: "reserved", name: "Reserved", type: "number", required: false },
        { slug: "inbound", name: "Inbound", type: "number", required: false },
        { slug: "inbound-eta", name: "Inbound ETA", type: "text", required: false },
        { slug: "days-cover", name: "Days cover", type: "number", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "review",
      name: "Review",
      slug: "busa-product-hub-review",
      description:
        "Approval-gated review queue: channel publish approvals, price-change review, quality holds, lifecycle/archive decisions, and spec-claim citations, linked to a product. The operator's decision (approve/request_changes/block) is written directly onto this row -- there is no separate decisions.json-equivalent bucket. Execution fields record the agent's follow-up outside the app after approval. `type: \"spec_claim\"` (see product-hub-model.js) flags a specification claim the agent extracted from an uploaded document without a clear page/section citation -- any products field or certificates row whose source-note doesn't cite a specific document+location should get one of these before it is trusted on a customer-facing quote.",
      readLimit: 50,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "recommendation", name: "Recommendation", type: "text", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "busa-product-hub-settings",
      description: "Seller profile, platform connectors, warehouses, and review policy -- a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "seller-brand", name: "Brand", type: "text", required: false },
        { slug: "seller-entity", name: "Entity", type: "text", required: false },
        { slug: "base-currency", name: "Base currency", type: "text", required: false },
        { slug: "platforms", name: "Platforms (JSON array)", type: "longtext", required: false },
        { slug: "warehouses", name: "Warehouses (JSON array)", type: "longtext", required: false },
        { slug: "review-policy", name: "Review policy (JSON object)", type: "longtext", required: false },
        { slug: "sync", name: "Sync (JSON object)", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "certificates",
      name: "Certificates",
      slug: "busa-product-hub-certificates",
      description:
        "One row per product certificate (CE/FCC/RoHS/UN38.3/UKCA/Other): issuer, certificate number, issued/expiry dates, the certificate file itself, and a source note. There is no stored status field -- expiring_soon/expired/valid is always derived client-side from expiry-date vs now, the same derived-not-stored pattern as this app's own SLA/status badges (see product-hub-model.js's certStatusFor).",
      readLimit: 50,
      fields: [
        {
          slug: "product",
          name: "Product",
          type: "relation",
          required: false,
          options: { targetBaseSlug: "products", multiple: false },
        },
        {
          slug: "cert-type",
          name: "Certificate type",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "CE", name: "CE" },
              { id: "FCC", name: "FCC" },
              { id: "RoHS", name: "RoHS" },
              { id: "UN38.3", name: "UN38.3" },
              { id: "UKCA", name: "UKCA" },
              { id: "Other", name: "Other" },
            ],
          },
        },
        { slug: "issuer", name: "Issuer", type: "text", required: false },
        { slug: "cert-number", name: "Certificate number", type: "text", required: false },
        { slug: "issued-date", name: "Issued date", type: "text", required: false },
        { slug: "expiry-date", name: "Expiry date", type: "text", required: false },
        {
          slug: "file",
          name: "Certificate file",
          type: "attachment",
          required: false,
          options: { attachment: { maxFiles: 1 } },
        },
        { slug: "source-note", name: "Source note", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.count"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    // The browser only ever decides on a review item (records.changeRequest);
    // it never creates a product/channel/inventory/certificate row -- those
    // enter Busabase through the operator's own workflow (directly, through
    // $busabase, or through an agent acting on the operator's behalf), never
    // through this AirApp. bases.createChangeRequest is unused from the
    // browser today but kept in the allow-list for symmetry with any future
    // trusted write path that reuses the same field-encoding helpers.
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
