export const appConfig = {
  appId: "busa-expo-leads",
  appName: "Busa Expo Leads",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Busa Expo Leads",
    description: "Trade-show lead capture, SLA countdown, and a multilingual follow-up review queue",
    slug: "busa-expo-leads",
  },
  airApp: { name: "Busa Expo Leads", slug: "busa-expo-leads-app", resourceKey: "busa-expo-leads-app" },
  bases: [
    {
      key: "batches",
      name: "Batches",
      slug: "busa-expo-leads-batches",
      description: "One row per trade show attended",
      readLimit: 50,
      fields: [
        { slug: "name", name: "Name", type: "text", required: true },
        { slug: "location", name: "Location", type: "text", required: false },
        { slug: "start-date", name: "Start date", type: "text", required: false },
        { slug: "end-date", name: "End date", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
      ],
    },
    {
      key: "leads",
      name: "Leads",
      slug: "busa-expo-leads-leads",
      description: "Booth leads captured the moment a buyer is met",
      readLimit: 50,
      fields: [
        { slug: "name", name: "Name", type: "text", required: true },
        { slug: "company", name: "Company", type: "text", required: false },
        { slug: "country", name: "Country", type: "text", required: false },
        {
          slug: "language",
          name: "Language",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "en", name: "English" },
              { id: "es", name: "Spanish" },
              { id: "ar", name: "Arabic" },
              { id: "zh", name: "Chinese" },
              { id: "other", name: "Other" },
            ],
          },
        },
        {
          slug: "batch",
          name: "Batch",
          type: "relation",
          required: false,
          options: { targetBaseSlug: "batches", multiple: false },
        },
        {
          slug: "card-photo",
          name: "Card photo",
          type: "attachment",
          required: false,
          options: { attachment: { maxFiles: 1 } },
        },
        { slug: "product-interest", name: "Product interest", type: "text", required: false },
        {
          slug: "contact-channel",
          name: "Contact channel",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "whatsapp", name: "WhatsApp" },
              { id: "email", name: "Email" },
              { id: "wechat", name: "WeChat" },
            ],
          },
        },
        { slug: "contact-handle", name: "Contact handle", type: "text", required: false },
        { slug: "met-at", name: "Met at", type: "text", required: false },
        {
          slug: "stage",
          name: "Stage",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "new", name: "New" },
              { id: "contacted", name: "Contacted" },
              { id: "replied", name: "Replied" },
              { id: "qualified", name: "Qualified" },
              { id: "lost", name: "Lost" },
            ],
            default: "new",
          },
        },
      ],
    },
    {
      key: "followups",
      name: "Follow-ups",
      slug: "busa-expo-leads-followups",
      description: "The review queue: drafted multilingual follow-ups awaiting a human decision before send",
      readLimit: 50,
      fields: [
        {
          slug: "lead",
          name: "Lead",
          type: "relation",
          required: false,
          options: { targetBaseSlug: "leads", multiple: false },
        },
        { slug: "language", name: "Language", type: "text", required: false },
        { slug: "draft-text", name: "Draft text", type: "longtext", required: false },
        {
          slug: "channel",
          name: "Channel",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "whatsapp", name: "WhatsApp" },
              { id: "email", name: "Email" },
              { id: "wechat", name: "WeChat" },
            ],
          },
        },
        {
          slug: "status",
          name: "Status",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "needs_review", name: "Needs review" },
              { id: "approved", name: "Approved" },
              { id: "sent", name: "Sent" },
            ],
            default: "needs_review",
          },
        },
        {
          slug: "decision-action",
          name: "Decision action",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "approve", name: "Approve" },
              { id: "request_changes", name: "Request changes" },
              { id: "block", name: "Block" },
            ],
          },
        },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "busa-expo-leads-settings",
      description: "SLA thresholds, default reply templates, and the channel accounts used to send follow-ups, one row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "sla-24h-hours", name: "SLA 24h hours", type: "number", required: false },
        { slug: "sla-72h-hours", name: "SLA 72h hours", type: "number", required: false },
        { slug: "reply-templates", name: "Reply templates", type: "longtext", required: false },
        { slug: "whatsapp-account-env", name: "WhatsApp account env", type: "text", required: false },
        { slug: "email-account-env", name: "Email account env", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.count"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
