export const demoNow = "2026-09-02T12:00:00.000Z";

export const demoRecords = [
  {
    id: "demo-company-northstar",
    baseKey: "companies",
    fields: {
      "company-name": "Northstar Analytics",
      website: "https://northstar-analytics.example",
      industry: "software-technology",
      "relationship-type": "prospect",
      "company-size": "51-200",
      headquarters: "Austin, TX",
      notes: "Evaluating a shared revenue workspace across sales and customer success.",
    },
  },
  {
    id: "demo-company-harborline",
    baseKey: "companies",
    fields: {
      "company-name": "Harborline Manufacturing",
      website: "https://harborline.example",
      industry: "manufacturing",
      "relationship-type": "customer",
      "company-size": "201-500",
      headquarters: "Rotterdam, Netherlands",
      notes: "Expanding an existing operations deployment into two additional plants.",
    },
  },
  {
    id: "demo-company-meridian",
    baseKey: "companies",
    fields: {
      "company-name": "Meridian Health Systems",
      website: "https://meridian-health.example",
      industry: "healthcare",
      "relationship-type": "prospect",
      "company-size": "501-1000",
      headquarters: "Copenhagen, Denmark",
      notes: "Scoping a three-site care coordination pilot with executive sponsorship.",
    },
  },
  {
    id: "demo-company-vela",
    baseKey: "companies",
    fields: {
      "company-name": "Vela Commerce Group",
      website: "https://vela-commerce.example",
      industry: "retail-ecommerce",
      "relationship-type": "customer",
      "company-size": "201-500",
      headquarters: "Paris, France",
      notes: "Customer account exploring a commerce data and support workflow expansion.",
    },
  },
  {
    id: "demo-company-bracken",
    baseKey: "companies",
    fields: {
      "company-name": "Bracken Ridge Financial",
      website: "https://bracken-financial.example",
      industry: "financial-services",
      "relationship-type": "prospect",
      "company-size": "1001-plus",
      headquarters: "Toronto, Canada",
      notes: "Reviewing security and compliance requirements for a risk operations workspace.",
    },
  },
  {
    id: "demo-company-alder",
    baseKey: "companies",
    fields: {
      "company-name": "Alder & Co Advisory",
      website: "https://alder-advisory.example",
      industry: "professional-services",
      "relationship-type": "partner",
      "company-size": "11-50",
      headquarters: "London, United Kingdom",
      notes: "Referral partner negotiating a joint enablement and account planning package.",
    },
  },
  {
    id: "demo-contact-maya",
    baseKey: "contacts",
    fields: {
      "full-name": "Maya Chen",
      company: "demo-company-northstar",
      "job-title": "VP, Revenue Operations",
      "buying-role": "decision-maker",
      email: "maya.chen@northstar-analytics.example",
      phone: "+1 512 555 0148",
      "linkedin-profile": "https://www.linkedin.com/in/maya-chen-example",
      "contact-status": "active",
      notes: "Owns the evaluation process and executive alignment.",
    },
  },
  {
    id: "demo-contact-lucas",
    baseKey: "contacts",
    fields: {
      "full-name": "Lucas Meyer",
      company: "demo-company-harborline",
      "job-title": "Director of Operations",
      "buying-role": "champion",
      email: "lucas.meyer@harborline.example",
      phone: "+31 10 555 0184",
      "contact-status": "active",
      notes: "Coordinates adoption across plant operations teams.",
    },
  },
  {
    id: "demo-contact-elena",
    baseKey: "contacts",
    fields: {
      "full-name": "Elena Rossi",
      company: "demo-company-meridian",
      "job-title": "Chief Digital Officer",
      "buying-role": "decision-maker",
      email: "elena.rossi@meridian-health.example",
      phone: "+45 33 55 01 42",
      "contact-status": "active",
      notes: "Executive sponsor for the regional pilot.",
    },
  },
  {
    id: "demo-contact-sophie",
    baseKey: "contacts",
    fields: {
      "full-name": "Sophie Laurent",
      company: "demo-company-vela",
      "job-title": "VP, Commerce Operations",
      "buying-role": "champion",
      email: "sophie.laurent@vela-commerce.example",
      phone: "+33 1 55 00 14 27",
      "contact-status": "active",
      notes: "Coordinates commerce operations and the expansion evaluation.",
    },
  },
  {
    id: "demo-deal-northstar-rollout",
    baseKey: "deals",
    fields: {
      "deal-name": "Northstar Revenue Workspace",
      company: "demo-company-northstar",
      "primary-contact": "demo-contact-maya",
      amount: 48000,
      currency: "usd",
      stage: "discovery",
      "expected-close-date": "2026-09-24",
      "next-step": "Confirm the technical evaluation workshop.",
      notes: "Initial multi-team rollout opportunity.",
    },
  },
  {
    id: "demo-deal-harborline-expansion",
    baseKey: "deals",
    fields: {
      "deal-name": "Harborline Plant Expansion",
      company: "demo-company-harborline",
      "primary-contact": "demo-contact-lucas",
      amount: 72000,
      currency: "eur",
      stage: "proposal",
      "expected-close-date": "2026-09-18",
      "next-step": "Review the expansion proposal with plant leadership.",
      notes: "Expansion across two additional facilities.",
    },
  },
  {
    id: "demo-deal-meridian-pilot",
    baseKey: "deals",
    fields: {
      "deal-name": "Meridian Coordination Pilot",
      company: "demo-company-meridian",
      "primary-contact": "demo-contact-elena",
      amount: 95000,
      currency: "eur",
      stage: "qualification",
      "expected-close-date": "2026-10-12",
      "next-step": "Confirm pilot locations and success criteria.",
      notes: "Initial care coordination pilot across three regional sites.",
    },
  },
  {
    id: "demo-deal-vela-data-hub",
    baseKey: "deals",
    fields: {
      "deal-name": "Vela Commerce Data Hub",
      company: "demo-company-vela",
      "primary-contact": "demo-contact-sophie",
      amount: 56000,
      currency: "eur",
      stage: "discovery",
      "expected-close-date": "2026-09-29",
      "next-step": "Complete the commerce data mapping workshop.",
      notes: "Expansion connecting commerce and support teams.",
    },
  },
  {
    id: "demo-deal-bracken-risk",
    baseKey: "deals",
    fields: {
      "deal-name": "Bracken Risk Workspace",
      company: "demo-company-bracken",
      amount: 84000,
      currency: "gbp",
      stage: "proposal",
      "expected-close-date": "2026-10-01",
      "next-step": "Review security requirements with risk leadership.",
      notes: "Risk collaboration workspace for policy and evidence reviews.",
    },
  },
  {
    id: "demo-deal-alder-enablement",
    baseKey: "deals",
    fields: {
      "deal-name": "Alder Partner Enablement",
      company: "demo-company-alder",
      amount: 30000,
      currency: "gbp",
      stage: "negotiation",
      "expected-close-date": "2026-09-12",
      "next-step": "Finalize the joint enablement scope.",
      notes: "Partner enablement and shared account planning package.",
    },
  },
  {
    id: "demo-deal-harborline-rollout",
    baseKey: "deals",
    fields: {
      "deal-name": "Harborline Operations Rollout",
      company: "demo-company-harborline",
      "primary-contact": "demo-contact-lucas",
      amount: 110000,
      currency: "eur",
      stage: "closed-won",
      "expected-close-date": "2026-08-28",
      "next-step": "Schedule the plant champion kickoff.",
      notes: "Signed rollout connecting plant procedures and operating knowledge.",
    },
  },
  {
    id: "demo-deal-northstar-pilot",
    baseKey: "deals",
    fields: {
      "deal-name": "Northstar Analytics Pilot",
      company: "demo-company-northstar",
      "primary-contact": "demo-contact-maya",
      amount: 18000,
      currency: "usd",
      stage: "closed-lost",
      "expected-close-date": "2026-08-27",
      "next-step": "Retain evaluation notes for future planning.",
      notes: "Pilot paused when the customer consolidated its tooling review.",
    },
  },
  {
    id: "demo-activity-harborline-review",
    baseKey: "activities",
    fields: {
      "activity-subject": "Harborline pilot success review",
      company: "demo-company-harborline",
      contact: "demo-contact-lucas",
      deal: "demo-deal-harborline-rollout",
      "activity-type": "note",
      "activity-date": "2026-08-27",
      summary: "Captured adoption outcomes and the expansion case.",
      "next-follow-up-date": "2026-09-03",
    },
  },
  {
    id: "demo-activity-northstar-discovery",
    baseKey: "activities",
    fields: {
      "activity-subject": "Discovery call with Northstar",
      company: "demo-company-northstar",
      contact: "demo-contact-maya",
      deal: "demo-deal-northstar-rollout",
      "activity-type": "call",
      "activity-date": "2026-08-28",
      summary: "Reviewed the rollout scope and evaluation criteria.",
      "next-follow-up-date": "2026-09-02",
    },
  },
  {
    id: "demo-activity-vela-mapping",
    baseKey: "activities",
    fields: {
      "activity-subject": "Vela data mapping follow-up",
      company: "demo-company-vela",
      contact: "demo-contact-sophie",
      deal: "demo-deal-vela-data-hub",
      "activity-type": "email",
      "activity-date": "2026-08-28",
      summary: "Confirmed commerce data owners and the discovery checklist.",
      "next-follow-up-date": "2026-09-04",
    },
  },
  {
    id: "demo-activity-alder-workshop",
    baseKey: "activities",
    fields: {
      "activity-subject": "Alder partner planning workshop",
      company: "demo-company-alder",
      deal: "demo-deal-alder-enablement",
      "activity-type": "meeting",
      "activity-date": "2026-08-29",
      summary: "Aligned the joint enablement scope and account planning topics.",
      "next-follow-up-date": "2026-09-05",
    },
  },
  {
    id: "demo-activity-meridian-alignment",
    baseKey: "activities",
    fields: {
      "activity-subject": "Meridian executive alignment",
      company: "demo-company-meridian",
      contact: "demo-contact-elena",
      deal: "demo-deal-meridian-pilot",
      "activity-type": "meeting",
      "activity-date": "2026-08-31",
      summary: "Aligned executive sponsors on pilot outcomes and governance.",
      "next-follow-up-date": "2026-09-07",
    },
  },
  {
    id: "demo-activity-bracken-security",
    baseKey: "activities",
    fields: {
      "activity-subject": "Bracken security checklist",
      company: "demo-company-bracken",
      deal: "demo-deal-bracken-risk",
      "activity-type": "email",
      "activity-date": "2026-08-31",
      summary: "Shared the security checklist and proposal review timeline.",
      "next-follow-up-date": "2026-09-01",
    },
  },
  {
    id: "demo-activity-harborline-handoff",
    baseKey: "activities",
    fields: {
      "activity-subject": "Harborline rollout handoff",
      company: "demo-company-harborline",
      contact: "demo-contact-lucas",
      deal: "demo-deal-harborline-rollout",
      "activity-type": "note",
      "activity-date": "2026-08-31",
      summary: "Documented implementation owners and the plant kickoff sequence.",
    },
  },
  {
    id: "demo-activity-northstar-workshop",
    baseKey: "activities",
    fields: {
      "activity-subject": "Northstar technical workshop",
      company: "demo-company-northstar",
      contact: "demo-contact-maya",
      deal: "demo-deal-northstar-rollout",
      "activity-type": "meeting",
      "activity-date": "2026-09-01",
      summary: "Mapped the technical evaluation path and integration questions.",
      "next-follow-up-date": "2026-09-02",
    },
  },
  {
    id: "demo-activity-vela-stakeholders",
    baseKey: "activities",
    fields: {
      "activity-subject": "Vela stakeholder call",
      company: "demo-company-vela",
      contact: "demo-contact-sophie",
      deal: "demo-deal-vela-data-hub",
      "activity-type": "call",
      "activity-date": "2026-09-01",
      summary: "Confirmed the customer operations stakeholders for discovery.",
      "next-follow-up-date": "2026-09-06",
    },
  },
  {
    id: "demo-activity-bracken-proposal",
    baseKey: "activities",
    fields: {
      "activity-subject": "Bracken proposal review",
      company: "demo-company-bracken",
      deal: "demo-deal-bracken-risk",
      "activity-type": "call",
      "activity-date": "2026-09-02",
      summary: "Reviewed proposal questions with risk leadership.",
      "next-follow-up-date": "2026-09-09",
    },
  },
  {
    id: "demo-activity-alder-terms",
    baseKey: "activities",
    fields: {
      "activity-subject": "Alder commercial terms follow-up",
      company: "demo-company-alder",
      deal: "demo-deal-alder-enablement",
      "activity-type": "email",
      "activity-date": "2026-09-02",
      summary: "Sent the revised commercial scope for final review.",
      "next-follow-up-date": "2026-09-03",
    },
  },
  {
    id: "demo-activity-meridian-notes",
    baseKey: "activities",
    fields: {
      "activity-subject": "Meridian pilot decision notes",
      company: "demo-company-meridian",
      contact: "demo-contact-elena",
      deal: "demo-deal-meridian-pilot",
      "activity-type": "note",
      "activity-date": "2026-09-02",
      summary: "Captured site selection questions for the next sponsor review.",
      "next-follow-up-date": "2026-09-10",
    },
  },
];
