export const samples = {
  expenses: [
    {
      key: "expenses-1",
      fields: {
        title: "September team travel",
        entity: "Lumen Studio",
        owner: "Lin Chen",
        status: "pending",
        amount: 1860,
        currency: "CNY",
        due: "2026-10-03",
        evidence: "Travel receipts TR-009 (synthetic)",
        approval: "",
        paidAt: "",
        notes: "Hotel invoice is missing. Hold until receipt is supplied.",
      },
    },
    {
      key: "expenses-2",
      fields: {
        title: "Office network renewal",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "approved",
        amount: 720,
        currency: "CNY",
        due: "2026-10-05",
        evidence: "Invoice INV-102 (synthetic)",
        approval: "Finance review FR-019 (synthetic)",
        paidAt: "",
        notes: "Approved for reimbursement; payment has not been confirmed.",
      },
    },
    {
      key: "expenses-3",
      fields: {
        title: "August stationery",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "paid",
        amount: 385,
        currency: "CNY",
        due: "2026-09-20",
        evidence: "Invoice INV-088 (synthetic)",
        approval: "Finance review FR-011 (synthetic)",
        paidAt: "2026-09-21",
        receipt: "SYN-RC-088",
        notes: "Payment receipt RC-088 verified (synthetic).",
      },
    },
    {
      key: "expenses-4",
      fields: {
        title: "Client workshop supplies",
        entity: "Lumen Studio",
        owner: "Lin Chen",
        status: "blocked",
        amount: 1240,
        currency: "CNY",
        due: "2026-10-01",
        evidence: "Receipt WS-023 (synthetic)",
        approval: "",
        paidAt: "",
        notes:
          "Receipt total 1,240 differs from requested invoice total 1,420.",
      },
    },
  ],
  invoices: [
    {
      key: "invoices-1",
      fields: {
        title: "Workshop invoice request",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "pending",
        amount: 16800,
        currency: "CNY",
        due: "2026-10-02",
        evidence: "Contract CT-204 (synthetic)",
        approval: "",
        invoice: "",
        notes: "Customer tax details are awaiting confirmation.",
      },
    },
    {
      key: "invoices-2",
      fields: {
        title: "Design retainer - September",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "approved",
        amount: 24000,
        currency: "CNY",
        due: "2026-10-03",
        evidence: "Contract CT-201 (synthetic)",
        approval: "Issuance review IR-014 (synthetic)",
        invoice: "",
        notes: "Approved, but invoice has not been issued.",
      },
    },
    {
      key: "invoices-3",
      fields: {
        title: "Support service - August",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "issued",
        amount: 9600,
        currency: "CNY",
        due: "2026-09-22",
        evidence: "Contract CT-197 (synthetic)",
        approval: "Issuance review IR-012 (synthetic)",
        invoice: "SYN-INV-197",
        notes:
          "Synthetic invoice registered; collection is tracked separately.",
      },
    },
  ],
  reports: [
    {
      key: "reports-1",
      fields: {
        title: "September operating actuals",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "review",
        period: "2026-09",
        currency: "CNY",
        revenue: 108000,
        cost: 76400,
        due: "2026-10-08",
        reviewer: "Maya Zhou",
        evidence: "September close pack SEP-26 (synthetic)",
        notes:
          "One vendor invoice remains outstanding. Figures are provisional.",
      },
    },
    {
      key: "reports-2",
      fields: {
        title: "August operating actuals",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "accepted",
        period: "2026-08",
        currency: "CNY",
        revenue: 98000,
        cost: 70300,
        due: "2026-09-08",
        reviewer: "Maya Zhou",
        evidence: "August close pack AUG-26 (synthetic)",
        notes:
          "Reviewer acceptance recorded on 2026-09-09; not an audited statement.",
      },
    },
    {
      key: "reports-3",
      fields: {
        title: "October close preparation",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "draft",
        period: "2026-10",
        currency: "CNY",
        revenue: 0,
        cost: 0,
        due: "2026-11-08",
        reviewer: "Maya Zhou",
        evidence: "",
        notes:
          "No actuals entered yet. Zero means unpopulated, not zero activity.",
      },
    },
  ],
  filings: [
    {
      key: "filings-1",
      fields: {
        title: "September periodic filing",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "preparing",
        period: "2026-09",
        due: "2026-10-15",
        evidence: "Operator reminder CAL-015 (synthetic)",
        reviewer: "Kai Wu",
        notes:
          "Illustrative operator-set deadline; confirm against current authority notice.",
      },
    },
    {
      key: "filings-2",
      fields: {
        title: "Quarterly filing evidence review",
        entity: "Lumen Studio",
        owner: "Kai Wu",
        status: "review",
        period: "2026-Q3",
        due: "2026-10-12",
        evidence: "Draft checklist Q3-26 (synthetic)",
        reviewer: "Maya Zhou",
        notes: "Review source documents before submission outside this app.",
      },
    },
    {
      key: "filings-3",
      fields: {
        title: "August filing receipt",
        entity: "Lumen Studio",
        owner: "Maya Zhou",
        status: "filed",
        period: "2026-08",
        due: "2026-09-15",
        evidence: "SYN-FILING-0826",
        reviewer: "Kai Wu",
        notes: "Synthetic acknowledgment recorded; no real filing occurred.",
      },
    },
  ],
};
